### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by tryagains** [CocoonIO/cocoon-template-phaser#1]
Testing device
5 inch, 1080p droid dna

I have tried this template with cocoon and there is two black bars on the top and bottom of the game. I have tried selecting "scale to fill" in cocoon settings but still get a black bar. Anyway to fix this issue?

**Comment by LibelulaV** [comment]
Hello, 

Was it using Canvas+ in the dev-app?

**Comment by tryagains** [comment]
Yes I tried both Canvas+ and the others
