### ISSUE TITLE
Tempalte not working- black screen on android

### ISSUE THREAD

**Issue by Likon84** [CocoonIO/cocoon-template-phaser#2]
this template is not working when compiled with cocoon.
Please fix..

**Comment by LibelulaV** [comment]
Do you mean in the new cloud? And what does the log says? Which android version? In which type of device? 
We need more information in order to locate the bug, because it works great in our tests.

**Comment by Likon84** [comment]
well I managed to run it. Just packed the www folder. Don't know why other files are in the project than. But it crashes first time the sounds is on. And also I see glitches.... Tried the newest cocoonjs 2.1.1

**Comment by LibelulaV** [comment]
Because it is not got cocoonjs. It is for Cocoon.io, the new cloud in beta. That is why it was crashing. In cocoonjs you just need the www folder.

**Comment by Likon84** [comment]
Hmmm what is this? :D some better cocoonjs? I cannot login there, can you send me an invitation on likon84@gmail.com please?

**Comment by keianhzo** [comment]
You can go to http://cocoon.io and ask for an invitation, it won't be long until your request is accepted.

**Comment by Likon84** [comment]
I got some welcome to beta mail, but I still can't login. No invitation mail to setup account either.

**Comment by keianhzo** [comment]
That means that the invitation mail is about to come.

**Comment by Likon84** [comment]
waiting few days, and still nothing....

**Comment by Likon84** [comment]
Ok I got it. Compiled the template. But still many glitches. Am I doing something wrong? The cocoonjs box2d example is mega smooth. But the template game has glitches, on my Galaxy S4.

**Comment by keianhzo** [comment]
What kind of glitches?. Could you send some screenshots?.

Thank you!

**Comment by Likon84** [comment]
Sorry maybe I expressed myself wrong. The game is not smooth, I see how ball sometimes stop for a milliseconds and than shows 2mm further. The ball flow is not smooth. It's gonna be hard to record it I think...

**Comment by keianhzo** [comment]
In what platform does it happen?. We have just removed an annoying alert that was showing each time the ball bounced. That was making the game laggy. Could you try again and let us know if that was the issue?.

Thanks for your feedback.

**Comment by Likon84** [comment]
I still have the "drops". I think the best it will be to see to create some tile image that will be moved constantly imitating the player move. And you will see it it not smooth, there will be drops.

**Comment by Likon84** [comment]
It happens on Android. Did you tried to make some examlpe with phaser and tilesprite that are moving?
